--- #YAML:1.0
name:                ExtUtils-ModuleMaker
version:             0.51
abstract:            Better than h2xs for creating modules
license:             ~
author:              
    - James E Keenan (jkeenan@cpan.org)
generated_by:        ExtUtils::MakeMaker version 6.42
distribution_type:   module
requires:     
    File::Basename:                0
    File::Path:                    0
    File::Save::Home:              0.03
    Getopt::Std:                   0
    Test::More:                    0.44
meta-spec:
    url:     http://module-build.sourceforge.net/META-spec-v1.3.html
    version: 1.3
